[project]
name = "llm-perplexity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.5.0",
    "langchain>=0.3.22",
    "langchain-openai>=0.3.11",
    "pyarrow==15.0.1",
    "python-dotenv>=1.1.0",
]
